#!/usr/bin/env python3
"""Slow, obvious B1 reference: HTML / PDF / LaTeX bytes -> text.

Rust tests call the public crate API, not this file. This exists so an
implementer can see the intended extraction, and so goldens can be
regenerated by hand.

Rules (spec 07, 15.5 B1):
  * empty input is an error (not modeled here; the crate returns Error::Empty)
  * undecodable / corrupt input is an error (UTF-8 for HTML/LaTeX; PDF parse)
  * HTML: strip tags, keep visible text, decode entities, drop script/style/comments
  * PDF: keep shown text
  * LaTeX: keep math as source ($...$, $$...$$, math environments), never
    approximate with Unicode (α, ∑, ², …)
"""

from __future__ import annotations

import hashlib
import html as html_lib
import re
import sys
from html.parser import HTMLParser
from pathlib import Path

MATH_ENVS = (
    "equation",
    "align",
    "alignat",
    "flalign",
    "gather",
    "multline",
    "eqnarray",
    "math",
    "displaymath",
)

SKIP_HTML_TAGS = frozenset({"script", "style", "noscript"})
BLOCK_HTML_TAGS = frozenset(
    {
        "br",
        "p",
        "div",
        "h1",
        "h2",
        "h3",
        "h4",
        "h5",
        "h6",
        "li",
        "tr",
        "title",
        "section",
        "article",
        "header",
        "footer",
        "blockquote",
        "pre",
        "ul",
        "ol",
        "table",
    }
)


class _HtmlText(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.parts: list[str] = []
        self._skip = 0

    def handle_starttag(self, tag: str, attrs) -> None:  # noqa: ANN001
        if tag in SKIP_HTML_TAGS:
            self._skip += 1
        if tag in BLOCK_HTML_TAGS:
            self.parts.append("\n")

    def handle_endtag(self, tag: str) -> None:
        if tag in SKIP_HTML_TAGS and self._skip:
            self._skip -= 1
        if tag in BLOCK_HTML_TAGS:
            self.parts.append("\n")

    def handle_data(self, data: str) -> None:
        if self._skip == 0:
            self.parts.append(data)

    def handle_comment(self, data: str) -> None:
        return


def extract_html(data: bytes) -> str:
    text = data.decode("utf-8")
    parser = _HtmlText()
    parser.feed(text)
    parser.close()
    return _collapse_blank_lines("".join(parser.parts))


def extract_latex(data: bytes) -> str:
    src = data.decode("utf-8")
    out: list[str] = []
    i = 0
    n = len(src)
    while i < n:
        ch = src[i]
        if ch == "%" and (i == 0 or src[i - 1] != "\\"):
            while i < n and src[i] != "\n":
                i += 1
            continue
        out.append(ch)
        i += 1
    return _collapse_blank_lines("".join(out))


def extract_pdf(data: bytes) -> str:
    """Pull literal strings shown with Tj/TJ. Obvious, not a full PDF parser."""
    if not data.lstrip().startswith(b"%PDF"):
        raise ValueError("not a PDF")
    parts: list[str] = []
    for match in re.finditer(rb"\((?:\\.|[^\\)])*\)\s*Tj", data):
        inner = match.group(0)
        inner = inner.rsplit(b"Tj", 1)[0].strip()
        assert inner.startswith(b"(") and inner.endswith(b")")
        payload = inner[1:-1]
        payload = (
            payload.replace(b"\\(", b"(")
            .replace(b"\\)", b")")
            .replace(b"\\\\", b"\\")
            .replace(b"\\n", b"\n")
        )
        parts.append(payload.decode("latin-1"))
    if not parts:
        raise ValueError("no text operators")
    return "\n".join(parts)


def preserves_latex_math(text: str) -> bool:
    if "$$" in text:
        return True
    for env in MATH_ENVS:
        if rf"\begin{{{env}}}" in text or rf"\begin{{{env}*}}" in text:
            return True
    i = 0
    while i < len(text):
        if text[i] == "$" and (i == 0 or text[i - 1] != "\\"):
            j = i + 1
            while j < len(text):
                if text[j] == "$" and text[j - 1] != "\\":
                    return True
                j += 1
            return False
        i += 1
    return False


def sha256_hex(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _collapse_blank_lines(text: str) -> str:
    text = html_lib.unescape(text)
    lines = [" ".join(line.split()) for line in text.splitlines()]
    lines = [line for line in lines if line]
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print("usage: extract.py <file>", file=sys.stderr)
        return 2
    path = Path(argv[1])
    data = path.read_bytes()
    suffix = path.suffix.lower()
    if suffix in {".html", ".htm", ".xhtml"}:
        print(extract_html(data))
    elif suffix == ".pdf":
        print(extract_pdf(data))
    elif suffix in {".tex", ".latex"}:
        print(extract_latex(data))
    else:
        print(f"unknown suffix {suffix}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
